version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: java-app
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/
    ports:
      - "8080:8080"

volumes:
  mongo-data:
